apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod-1
  namespace: default
spec:
  containers:
    - name: app
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod-2
  namespace: default
spec:
  containers:
    - name: app
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod-1
  namespace: monitoring
spec:
  containers:
    - name: prometheus
      image: prom/prometheus
